//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhoThong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIAHANHKIEM
    {
        public string MaHS { get; set; }
        public string GiaoVienDanhGia { get; set; }
        public string MaHKiem { get; set; }
        public string MaNH { get; set; }
        public Nullable<int> DiemSo { get; set; }
    
        public virtual HANHKIEM HANHKIEM { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
    }
}
