//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhoThong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIEM()
        {
            this.DANHHIEUx = new HashSet<DANHHIEU>();
        }
    
        public int MaBD { get; set; }
        public string DiemMieng { get; set; }
        public string Diem15p { get; set; }
        public string Diem1Tiet { get; set; }
        public string DiemThi { get; set; }
        public int MaHS { get; set; }
        public int MaMH { get; set; }
        public int MaHK { get; set; }
        public string DiemTB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHHIEU> DANHHIEUx { get; set; }
        public virtual HOCKY HOCKY { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
    }
}
