//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhoThong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEMDANH
    {
        public string MaHS { get; set; }
        public int NghiCoPhep { get; set; }
        public int NghiKhongPhep { get; set; }
        public int BoTiet { get; set; }
        public string GhiChu { get; set; }
        public int IDDiemDanh { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
    }
}
