//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhoThong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAOVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAOVIEN()
        {
            this.LOPCHUNHIEMs = new HashSet<LOPCHUNHIEM>();
            this.Users = new HashSet<User>();
            this.PHANCONGs = new HashSet<PHANCONG>();
        }
    
        public string MaGV { get; set; }
        public string TenGV { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string SDT { get; set; }
        public string GioiTinh { get; set; }
        public string Gmail { get; set; }
        public string Diachi { get; set; }
        public string TrangThai { get; set; }
        public int idDanToc { get; set; }
        public string Thumb { get; set; }
    
        public virtual DanToc DanToc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOPCHUNHIEM> LOPCHUNHIEMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
    }
}
