//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhoThong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANHKIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANHKIEM()
        {
            this.DANHGIAHANHKIEMs = new HashSet<DANHGIAHANHKIEM>();
        }
    
        public string MaHKiem { get; set; }
        public int MaDMHK { get; set; }
        public string TenHKiem { get; set; }
        public int DiemToiDa { get; set; }
    
        public virtual DANHMUCHANHKIEM DANHMUCHANHKIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIAHANHKIEM> DANHGIAHANHKIEMs { get; set; }
    }
}
