//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhoThong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUACANAM
    {
        public string MaHS { get; set; }
        public string MaNH { get; set; }
        public Nullable<double> TBMCN { get; set; }
        public string HocLuc { get; set; }
        public string HanhKiem { get; set; }
        public string XepLoai { get; set; }
        public string TrangThai { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
    }
}
