//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhoThong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUAHOCKY
    {
        public string MaHS { get; set; }
        public Nullable<double> TBMHK { get; set; }
        public string MaHK { get; set; }
        public string MaNH { get; set; }
        public string Xeploai { get; set; }
    
        public virtual HOCKY HOCKY { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
    }
}
