//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhoThong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHAOSATDANHGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHAOSATDANHGIA()
        {
            this.DANHHIEUx = new HashSet<DANHHIEU>();
        }
    
        public int MaKSDG { get; set; }
        public int MaDMKSDG { get; set; }
        public int MaHS { get; set; }
        public int MaGV { get; set; }
        public string ThongTinKS { get; set; }
        public string MucDoDG { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHHIEU> DANHHIEUx { get; set; }
        public virtual DANHMUCKHAOSATDANHGIA DANHMUCKHAOSATDANHGIA { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual GIAOVIEN GIAOVIEN { get; set; }
    }
}
