//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhoThong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUPHI
    {
        public string MaThu { get; set; }
        public string MaHKy { get; set; }
        public string MaHS { get; set; }
        public string MucPhi { get; set; }
        public string Status { get; set; }
        public string idMaThu { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual HOCKY HOCKY { get; set; }
    }
}
