//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhoThong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int IDUser { get; set; }
        [Required]
        [Display(Name = "Tên đăng nhập")]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Mật khẩu")]
        public string PassWord { get; set; }
        public int MaTitleUser { get; set; }
        public int MaGV { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual TITLEUSER TITLEUSER { get; set; }
    }
}
